sudo: false
dist: xenial
lang: bash

install:
  - curl -sSfL -o /tmp/terraform.zip "https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip"
  - unzip /tmp/terraform.zip -d "$HOME/bin"
  - terraform --version
  - shellcheck --version

script:
  - ./runtests.sh
